spring:
  application:
    name: easy-base
  
  datasource:
    url: jdbc:postgresql://localhost:5432/easybase
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  profiles:
    active: development

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.easybase: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
