logging:
    level:
        com.easybase: DEBUG
        org.hibernate: INFO
        org.springframework.web: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: easy-base
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/easybase
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    profiles:
        active: development